# Generated by Django 2.2 on 2020-11-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('scoure', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sex', models.IntegerField(choices=[(1, '男'), (0, '女')])),
            ],
        ),
    ]
