# Generated by Django 2.2 on 2020-11-21 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
