# Generated by Django 2.2 on 2020-11-21 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
    ]
