# Generated by Django 2.2 on 2020-11-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default='aaa', max_length=254),
            preserve_default=False,
        ),
    ]
